name: Dependencies

on:
  workflow_dispatch:
    inputs:
      output-branch:
        type: string
        description: "Output branch"
        required: true
        default: with-deps

jobs:
  run-obfuscator:
    uses: CFC-Servers/gm_gh_dependencies/.github/workflows/gm_gh_deps.yml@main
    with:
      output-branch: ${{ github.event.inputs.output-branch }}
